### PR TITLE
use Conventional format, use types from config

### PR DESCRIPTION
**Pull request by dominicrico**
- fixes conventional format not used if set in config from package.json
- fixes types not used from config in commit message

### CODE REVIEW

**Comment by dominicrico** [comment]
If possible remove the latest commit that was just for me

**Comment by nicubarbaros** [comment]
looks like the project is dead :)

**Comment by wujekbogdan** [comment]
Is there any chance to merge this PR?

**Comment by ngryman** [comment]
Thanks for the PR @dominicrico.

I just merged the base branch. That's why this PR has been closed automatically. I addressed the issues you fixed here and credited you in the commits instead 👍

**Pull request closed without merging**
