### PR TITLE
Add the ability to specify subject maximum length

### PR DESCRIPTION
**Pull request by ngryman**
Re #28,

@RikardGehlin here is a pretty simple implementation that allow you to specify a `subjectMaxLength` configuration option. The `subject` prompt is now using: https://github.com/jwarby/inquirer-maxlength-input-prompt.

Would you mind giving it a try by referencing `ngryman/cz-emoji#subject-maxlen` as the version? Thanks!

### CODE REVIEW

**Comment by RikardGehlin** [comment]
Counts the inputs of the subject just fine. I like that it changes colors as you get closer and closer to the limit. Really nice touch!

A question though, maybe someone more experienced in git would be able to answer... shouldn't the length of the entire subject be counted? ie the icon and all the characters in the scope (and inserted whitespaces)

**Comment by ngryman** [comment]
@RikardGehlin Yes you are absolutely right, this is a pretty naive implementation.

We need to prefix the Emoji and potential scope too if we want to count the total length. The only way to achieve that with the `inquirer-maxlength-input-prompt` plugin is to use the `filter` method which would basically prepend the `type` and `scope` to the prompt. I found it to be visually annoying, to be honest. I figured out that people could tweak the maximum length in their configuration to find a sweet spot that works for their use case. However, I reckon that's not ideal...

You can try the `filter` method locally if you want. Let me know what do you think about prepending the `type` and `scope` before. If you think that's fine, perhaps I can prepend it then.

I could also propose a PR to the author of `inquirer-maxlength-input-prompt` so we can count an input without having to prepend anything visually.

**Comment by ngryman** [comment]
@RikardGehlin You are absolutely right, it was a very simple/naive implementation.

Using the Inquirer plugin to count the subject as a whole (with `type` and `scope`) was causing a side-effect I didn't really want to deal with. You can have more details about this side-effect in this commit's description: 6104dcb

But your comment highlights that this implementation will probably not be good enough, and I agree with that. So I ended up implementing it anyway.

Let me know if this implementation works for you.

**Comment by RikardGehlin** [comment]
hmm, it seems to be slightly off in the calculations. 

just type and scope: 
image

type, scope, and 1 character subject
image

after that though the counting seems alright

**Comment by RikardGehlin** [comment]
Type counts as 2 characters (emoji + space). 
Scope counts gives two extra (spaces around?). 
Subject adds one character when starting to type (extra space as well?).

This behavior exists even if you skip the scope or not.

**Comment by RikardGehlin** [comment]
ah, I think the major confusion from end comes the fact that in my mind the subject *has* to be answered, but you can actually just skip it.. so it makes sense to only add the spacing between header elements (type/scope/subject) when they are actually added. 

It feels a bit off that the scope counts jumps 2 for me though, but makes sense when thinking about it...

Input?

**Comment by ngryman** [comment]
@RikardGehlin Hey sorry for the late answer, I didn't have a lot of free time this week.

If I understand your feedback correctly, it feels a bit off that characters we don't see in the prompt (spaces and wrapping parenthesis) are also counted, is that right? One thing I could do is to prepend the already formatted type + scope to clarify this. I actually initially did that, but I felt that it was cluttering the prompt. Now given your feedback, I suppose it's necessary, otherwise it's confusing.

What do you think? Do you have other ideas?

**Comment by RikardGehlin** [comment]
For me, the confusing part is that it says 8/75 when getting to input the subject, but once I type 1 character the count jumps up to 10/75. It makes sense when you think about it adding a space between what's already there and what's coming (and needing a  space between) so maybe I'm just looking at it too hard and it's super obvious for everyone else :P 
I agree that adding the type and scope to the prompt would be a bit much

**Comment by ngryman** [comment]
Alright thanks for the clarification! I think I will default to ship this for now, and if someone else brings up that this is confusing I will revisit that implementation (and perhaps used a home made plugin). Does it sounds reasonable to you?

**Comment by RikardGehlin** [comment]
I'd be fine with that.

**Comment by RikardGehlin** [comment]
ping? :)

**Comment by RikardGehlin** [comment]
another ping?

**Comment by RikardGehlin** [comment]
Hey man, hope you had a nice christmas and new year. Anyway to get this merged and a new release anytime soon? O:)

**Comment by ngryman** [comment]
Hey @RikardGehlin ,

Sure thing merged and published 🎉
Sorry for this period of silence, I've been off screens for quite a bit during this period 😄

**Comment by RikardGehlin** [comment]
No worries, it's alright. I'm well aware of how the world of open source can work sometime. 😊 Nice to see you back and to have the code merged 👍
​​​​​​​

**Pull request merged**
